DROP TABLE student;
CREATE TABLE student (
student_id INT,
name VARCHAR(20) NOT NULL,
major VARCHAR(20) UNIQUE,
PRIMARY KEY(student_id)
);
SELECT * FROM student ;
INSERT INTO student VALUES(1,'JACK','BIOLOGY');
INSERT INTO student VALUES(2,'JASON','CHEMISTRY');
INSERT INTO student VALUES(3,'PHILL','COMPUTER SCIENCE');
INSERT INTO student VALUES(6,'FLORIDA','ALGEBRA');
INSERT INTO student VALUES(5,'SHELBY','STATS');
DESCRIBE student; 